[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "21"

[build]
  publish = "dist"
  command = "npx pnpm i && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
